awsRegion: 'ca-central-1'
mongoDBHost: 192.168.86.24
mongoDBName: 'universal-sales-test'
mongoDBPassword: null
mongoDBPort: 27017
mongoDBReplset: null
mongoDBUsername: null
PDFCreateURLURI: ''
PDFSaveURI: ''
s3Bucket: 'ca-universalwindows'
ssmPath: 'universal-api'
nodeEnv: 'prod'
usessm: true